---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: image-registry-credentials
  namespace: manuela-ci
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: image-registry-credentials
    template:
      metadata:
        annotations:
          # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
          tekton.dev/docker-0: https://{{ .Values.global.imageregistry.hostname }}
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: {{ .Values.imageregistrysecret.key }}
