global:
  imageregistry:
    hostname: quay.io

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3secret:
  key: secret/data/hub/aws
  namespaces:
    - external-secrets
    - edge-datalake

