- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: amq-streams-operator
        path: components/operators/amq-streams-operator/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: grafana
        path: components/operators/grafana/operator/overlays/v4
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: elasticsearch-operator
        path: components/operators/elasticsearch/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: opendatahub-operator
        path: components/operators/opendatahub/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: openshift-data-foundation-operator
        path: components/operators/openshift-data-foundation/aggregate/overlays/aws-node-labeler-4.12
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: openshift-pipelines-operator
        path: components/operators/openshift-pipelines/operator/overlays/latest
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: prometheus-user-workload-monitoring
        path: components/operators/prometheus-monitoring/instance/overlays/user-workload-monitoring/
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: rhods-operator
        path: components/operators/rhods-operator/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: seldon-operator
        path: components/operators/seldon/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: web-terminal-operator
        path: components/operators/web-terminal-operator/operator/overlays/fast
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: prometheus-operator
        path: components/operators/prometheus-operator/operator/overlays/beta
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: prometheus-instance
        path: components/operators/prometheus-operator/instance/overlays/example