kind: Service
apiVersion: v1
metadata:
  name: engine-room-monitoring-olympic
  namespace: edge-anomaly-detection
  labels:
    app: engine-room-monitoring-olympic
    app.kubernetes.io/component: engine-room-monitoring
    app.kubernetes.io/instance: engine-room-monitoring
    app.kubernetes.io/name: engine-room-monitoring-olympic
    app.kubernetes.io/part-of: engine-room-monitoring-olympic
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: engine-room-monitoring-olympic
    deployment: engine-room-monitoring-olympic
