kind: Service
apiVersion: v1
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    deploymentconfig: prod-kafka-cluster-kafdrop