kind: Deployment
apiVersion: apps/v1
metadata:
  name: mock-railroad-freight
  namespace: edge-anomaly-detection
  labels:
    app: mock-railroad
    app.kubernetes.io/component: mock-railroad
    app.kubernetes.io/instance: mock-railroad
    app.kubernetes.io/name: mock-railroad
    app.kubernetes.io/part-of: mock-railroad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-railroad
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mock-railroad
        deployment: mock-railroad-freight
    spec:
      containers:
        - name: mock-railroad
          image: >-
            image-registry.openshift-image-registry.svc:5000/edge-anomaly-detection/mock-railroad:latest
          env:
            - name: KAFKA_BROKER
              value: >-
                prod-kafka-cluster-kafka-bootstrap.edge-datalake.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: freight
            - name: KP
              value: '0.5'
            - name: KI
              value: ' 0.01'
            - name: KD
              value: '0.05'
            - name: ACCELERATION_DURATION
              value: '60'
            - name: TARGET_SPEED
              value: '65'
            - name: SPEED_TOLERANCE
              value: '2'
            - name: MIN_INITIAL_SPEED
              value: '20'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
