apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-to-s3-config
  namespace: edge-datalake
data:
  application.properties: |

    kafka.broker.uri={{ .Values.kafka.broker.uri }}
    kafka.broker.topic.enginetemperature={{ .Values.kafka.broker.topic.enginetemperature }}
    kafka.broker.topic.enginepressure={{ .Values.kafka.broker.topic.enginepressure }}
    kafka.broker.topic.enginerpm={{ .Values.kafka.broker.topic.enginerpm }}
    kafka.broker.topic.enginefuelconsumption={{ .Values.kafka.broker.topic.enginefuelconsumption }}
    kafka.broker.topic.outsidetemperature={{ .Values.kafka.broker.topic.outsidetemperature }}
    kafka.broker.topic.humidity={{ .Values.kafka.broker.topic.humidity }}
    kafka.broker.topic.windspeed={{ .Values.kafka.broker.topic.windspeed }}
    kafka.broker.topic.waveheight={{ .Values.kafka.broker.topic.waveheight }}


    s3.region={{ .Values.global.s3.bucket.region }}
    s3.bucket.name={{ .Values.global.s3.bucket.name }}
    s3.message.aggregation.count={{ .Values.global.s3.bucket.message.aggregation.count }}
    s3.custom.endpoint.enabled={{ .Values.global.s3.bucket.custom.endpoint.enabled }}
    # Convert this directory into a helm chart and use templating to set this
    s3.custom.endpoint.url=s3-openshift-storage.{{ .Values.global.localClusterDomain }}


