apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../../operator/overlays/stable-4.12
  - ../../../instance/overlays/aws-4.12
  - ../../../config-helpers/node-labeler/overlays/default
