apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogImVuZ2luZS1yb29tLW1vbml0b3JpbmciCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOiBbImVuZ2luZS1yb29tLW1vbml0b3JpbmcuZWRnZS1hbm9tYWx5LWRldGVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo4MDgwIl0=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
