apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogImVuZ2luZS1yb29tLW1vbml0b3Jpbmctb2x5bXBpYyIKICBzdGF0aWNfY29uZmlnczoKICAtIHRhcmdldHM6IFsiZW5naW5lLXJvb20tbW9uaXRvcmluZy1vbHltcGljLmVkZ2UtYW5vbWFseS1kZXRlY3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6ODAwMCJd
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
