kind: Deployment
apiVersion: apps/v1
metadata:
  name: engine-room-monitoring
  namespace: edge-anomaly-detection
  labels:
    app: engine-room-monitoring
    app.kubernetes.io/component: engine-room-monitoring
    app.kubernetes.io/instance: engine-room-monitoring
    app.kubernetes.io/name: engine-room-monitoring
    app.kubernetes.io/part-of: engine-room-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-room-monitoring
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: engine-room-monitoring
        deployment: engine-room-monitoring
    spec:
      containers:
        - name: engine-room-monitoring
          image: >-
            image-registry.openshift-image-registry.svc:5000/edge-anomaly-detection/engine-room-monitoring:latest
          env:
            - name: KAFKA_BROKER
              value: >-
                prod-kafka-cluster-kafka-bootstrap.edge-datalake.svc.cluster.local:9092
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
