global:
  datacenter:
    clustername: datacenter-XXXXX
    domain: BASEDOMAIN

  s3:
    bucket:
      name: BUCKETNAME
      region: AWSREGION
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false

clusterGroup:
  name: datacenter
  isHubCluster: true
  managedClusterGroups:
    factory:
      name: factory
      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
      # targetRevision: main
      helmOverrides:
      # Values must be strings!
      - name: clusterGroup.isHubCluster
        value: "false"
      clusterSelector:
#        matchLabels:
#          clusterGroup: factory
        matchExpressions:
        - key: vendor
          operator: In
          values:
            - OpenShift

# List of Kafka topics to be created
# Ships: "Titanic", "QueenMary","Olympic","Lusitania", "Britannic","Aurora","Polaris","Voyager","Endeavor","Nautilus"
# Trains: "bullet", "express", "freight", "Maglev", "Metro", "Passenger", "Steam", "Subway", "TGV", "Tram"
kafka:
  broker:
    uri: "prod-kafka-cluster-kafka-bootstrap.edge-datalake.svc.cluster.local:9092"
    topic:
      topicname: "Olympic"